USE [ApplicationVersions]
GO

SET IDENTITY_INSERT [dbo].[Server] ON 

INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (1, N'TEA4SVDUSKY', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (2, N'TEA4SVCOBRA', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (3, N'TEA4SVMUDPUPPY', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (4, N'TEA4SVTADPOLE', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (5, N'TEA4SVPIRANHA', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (6, N'TEA4SVDOGFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (7, N'TEA4SVRAPTOR', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (8, N'TEA4SVKINNEY', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (9, N'TEA4SVFLOUNDER', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (10, N'TEA4SVSKATE', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (11, N'TEA4SVSHARK', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (12, N'TEA4SVBOXTURTLE', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (13, N'TEA4SVDRAGON', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (14, N'TEA4SVTORTOISE', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (15, N'TEA4AVHOLLY', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (16, N'TEA4AVWAYLON', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (17, N'TEA4SVBULLFROG', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (18, N'burnett', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (19, N'johnson', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (20, N'PeimsServerGroup', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (21, N'TEA4AVBELL1 ', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (22, N'TEA4AFSHR02', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (23, N'TEA4SVNEWT', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (24, N'TEA4AVTSDSPAPP1', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (25, N'TEA4AVJOHNSTON', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (26, N'TEA4AVFAWCETT ', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (27, N'TEA4SVTREEFROG', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (28, N'TEA4AVWALLER', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (29, N'TEA4SVSTARFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (30, N'TEA4AVBROWN', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (31, N'TEA4AVOSWALD', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (32, N'TEA4AVPECOS ', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (33, N'TEA4SVANGELFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (34, N'TEA4SVBLACKFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (35, N'tea4avallred', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (37, N'TEA4AVBAIRD', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (38, N'SQLOnly', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (39, N'TEA4AVKIRK', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (40, N'TEA4SVLOVE ', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (41, N'SPARE', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (42, N'TEA4SVRAZORFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (43, N'tea4sviwas1dev', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (44, N'TEA4SVCATFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (45, N'TEA4AVHONESTY', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (46, N'TEA4SVSIMON', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (47, N'TEA4SVYOUTH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (48, N'TEA4AVRUSH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (49, N'TEA4SVRICO', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (50, N'TEA4SVMINNOW', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (51, N'TEA4SVGUPPY', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (52, N'TEA4SVKNIFEFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (53, N'TEA4SVLUNGFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (54, N'TEA4SVBLOBFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (55, N'TEA4SVBULLFISH', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (56, N'TEA4SVPIKE', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (57, N'TEA4SVCANETOAD', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (58, N'TEA4SVTRUETOAD', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (59, N'TEA4SVANACONDA', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (60, N'TEA4AVTSDSEAP1', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (61, N'TEA4AVTSDSEAP2', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (62, N'TEA4AVTSDSPMS1', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (63, N'TEA4AVTSDSPMS2', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (64, N'TEA4AVTSDSPAPP2', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (65, N'TEA4AVKYLE', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (66, N'TEA4AVJORDAN', 1)
INSERT [dbo].[Server] ([ID], [Name], [StatusTypeID]) VALUES (67, N'TEA4SVBETA', 1)
SET IDENTITY_INSERT [dbo].[Server] OFF