USE [ApplicationVersions]
GO

SET IDENTITY_INSERT [dbo].[Application] ON 

INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (1, N'tsdspeims', 3, 1, N'rel1730', N'PEIMS')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (2, N'FSP', 15, 1, N'rel1650', N'Foundation School Programs')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (5, N'eGrants', 4, 1, N'rel1234', N'eGrants Maintenance')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (7, N'tsdspeimsreports', 3, 1, N'rel1234', N'PEIMS Reports')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (8, N'tsdsreports', 3, 1, N'rel1730', N'TSDS Reports')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (9, N'CEMS', 5, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (10, N'CISApp', 2, 1, NULL, N'CIS App')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (11, N'EcosWeb', 17, 1, NULL, N'Ecos Web')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (12, N'eGrantsApp', 4, 1, N'rel1709', N'eGrants App')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (13, N'SbecWeb', 17, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (14, N'eGrantsDocImportService', 4, 1, NULL, N'eGrants Doc Import Service')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (15, N'ISAM', 9, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (16, N'HCF', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (17, N'PFAI', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (18, N'ORG', 11, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (19, N'TXCHSE', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (20, N'AskTedAdmin', 11, 1, NULL, N'AskTed Admin')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (21, N'TEReportAgent', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (22, N'trexparticipantadmin', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (23, N'BusinessPartnerAdmin', 11, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (24, N'EcosBatch', 17, 1, NULL, N'Ecos Batch')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (25, N'TRex', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (26, N'tsdsccdsreports', 3, 1, NULL, N'CCDS Reports')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (27, N'SPPI', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (29, N'CCLC', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (30, N'orgwebservice', 11, 1, NULL, N'ORG Web Service')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (31, N'eGrantsWorkflow', 4, 1, NULL, N'eGrants Workflow')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (32, N'TSF', 15, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (33, N'TPEIR', 13, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (34, N'CSTS', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (35, N'budgetanalysistool', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (36, N'PIRTS', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (37, N'tsdsgrv', 3, 1, N'rel1731', N'TSDS GRV')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (38, N'HRRS', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (39, N'FIRST ', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (40, N'Audit ', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (41, N'eGrantsGAA', 4, 1, NULL, N'eGrants GAA')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (42, N'eGrantsAspForms', 4, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (43, N'CharterFirst', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (44, N'HR', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (45, N'hrrsoeemailer', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (46, N'hrrsoeadmatch', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (47, N'hrrsoe', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (48, N'PAF', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (49, N'CIS', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (50, N'tsdsuid', 3, 1, NULL, N'TSDS UID')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (51, N'eGrantsReports', 4, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (53, N'tsdspeimspiduidconverter', 3, 1, NULL, N'TSDS PEIMS UidPidReplicator')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (54, N'egrantsreportinterface', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (55, N'eGrantsWebService', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (56, N'egrantsgrantopportunities', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (57, N'tsdsccds', 3, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (58, N'SPEDCDRMS', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (59, N'scmversioning', 12, 1, N'rel1736', N'SCM Versioning Database')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (60, N'IAM', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (61, N'examsvcs', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (62, N'tfsecurityhelper', 1, 1, N'rel1736', N'TeamForge Security Helper')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (64, N'TeamForge', 12, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (65, N'eGrantsPdfService', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (66, N'tsdsportal', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (67, N'CDRMS', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (68, N'ARMS', 10, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (69, N'tsdsstudentgpsdashboards20', 3, 1, N'rel1768', N'Dashboards UI')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (70, N'tsdsddmetl20', 3, 1, N'rel1768', N'Dashboards ETL')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (71, N'waivers', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (72, N'tsdsstudentgpsdashboards', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (73, N'tsdspidwebservice', 1, 1, NULL, NULL)
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (74, N'tfmetrics', 12, 1, N'rel1774', N'TeamForge Metrics')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (75, N'tsdspeimsvalidationrules', 3, 1, NULL, N'PEIMS Validation Rules')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (76, N'validationframework', 7, 1, NULL, N'Shared Validation Rules Framework')
INSERT [dbo].[Application] ([ID], [Name], [ProjectID], [StatusTypeID], [ActiveTFRelease], [DisplayName]) VALUES (77, N'pafhrforms', 1, 1, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Application] OFF